
Interact_Text_Y_Offset = 200

Doors_Interact_Check_Interval_ms = 500
Doors_Interact_Check_Trace_Distance_Max = 175

Barricades_Interact_Check_Interval_ms = 1250
Barricades_Interact_Check_Distance_Squared_Max = 22500
Repair_Barricade_Interval_ms = 1750

DownPlayer_Interact_Check_Interval_ms = 550
DownPlayer_Interact_Check_Distance_Squared_Max = 22500

MBOX_Interact_Check_Interval_ms = 650
MBOX_Interact_Check_Distance_Squared_Max = 22500

POWER_Interact_Check_Interval_ms = 1000
POWER_Interact_Check_Distance_Squared_Max = 40000

Perk_Interact_Check_Interval_ms = 600
Perk_Interact_Check_Distance_Squared_Max = 40000

PAP_Interact_Check_Interval_ms = 800
PAP_Interact_Check_Distance_Squared_Max = 40000

Wunderfizz_Interact_Check_Interval_ms = 750
Wunderfizz_Interact_Check_Distance_Squared_Max = 40000

Wunderfizz_Bottle_Interact_Check_Interval_ms = 850
Wunderfizz_Bottle_Interact_Check_Distance_Squared_Max = 35000

Custom_Interact_Check_Interval_ms = 625

Teleporters_Interact_Check_Interval_ms = 900

Gibs_Interact_Check_Interval_ms = 1000
Gibs_Interact_Check_Distance_Squared_Max = 14400

VPAD_Interact_Check_Interval_ms = 950
VPAD_Interact_Check_Distance_Squared_Max = 40000